### ISSUE TITLE
Implémenter le parrainage

### ISSUE THREAD

**Issue by pfreund** [CarbonFight/actions#13]
Un système de parrainage simple doit être implémenté.
L'idée est de permettre de l'utilisateur **sponsor** de partager un **sponsorship_code** sous la forme XXXX-XXXX (à challenger).
Le filleul entre son code parrain dans l'application, ce code est écrit dans le champ **sponsor** de la collection users.

A minima, il faut calculer le nombre de filleul de la personne, dans un champ dans la collections stats.

**Comment by Jdevvv** [comment]
@pfreund Est-ce que c'est ce que tu avais en tête ?

<img width="1932" alt="Sponsorship sequence" src="https://github.com/CarbonFight/actions/assets/39907637/30d19968-210f-4b20-95dc-6434ee816bfb">

**Comment by pfreund** [comment]
Oui c'est ca. Deux petites corrections :
- Le code de UID 1 peut être ajouté par UID 2 n'importe quand dans ses paramètres. Ce n'est pas lors du "register".
- Les fonctions de stats ne se déclenchent qu'à la modification de la table users. Les deux tâches oranges sont en série et non en parallèle.

Tu peux aussi ajouter le calcul du challenge (un troisième carré orange), qui se déclenchera quand la table stats sera mise à jour. Et les challenges seront à "true" si le compteur de stats dépasse un seuil.

**Comment by pfreund** [comment]
Attention il ne faudra que le compteur se décrémente si l'utilisateur retire son code sponsor ou le modifie.

**Comment by Jdevvv** [comment]
@pfreund J'ai mis à jour le diagramme, petite question sur le `sponsorship_code` d'un utilisateur, est-ce qu'on doit le créer dans une Cloud function qui se déclenche sur un onUserCreate ou est-ce qu'il est créé à ailleurs à l'inscription d'un utilisateur?
<img width="2092" alt="Sponsorship sequence (1)" src="https://github.com/CarbonFight/actions/assets/39907637/483634fc-56c9-4991-bfd7-f12ea848786a">

**Comment by pfreund** [comment]
C'est bien à la création de l'utilisateur. Le schéma est tout à fait correct.
Dans un premier temps, c'est OK s'il n'y a pas de vérification si le sponsoship_code n'est pas déjà utilisé, ou si le code fait un mot inapproprié. Avec 8 caractères alphabétiques, on est déjà sur 208 milliards de possibilité ce qui rend peu probable ces cas.

**Comment by pfreund** [comment]
En fait l'action Generate Sponsorship_code, je peux la faire très facilement côté front.
Tu n'as pas besoin de le faire côté back.
