### ISSUE TITLE
Auto-validation des documents Action & Users

### ISSUE THREAD

**Issue by pfreund** [CarbonFight/actions#25]
Lorsque l'application dispose d'une mauvaise connexion (mobile), ou que la connexion s'arrête subitement, il arrive que les documents soient écrits partiellement.
Il peut manquer des champs comme CO2e, ce qui génère des erreurs. Les fonctions de calcul des statistiques plantent, et inscrivent "NaN", et fait planter l'application mobile (écran gris).

Il faut créer des fonctions qui vérifient que tous les champs sont bien renseignés, et dans le cas contraire suppriment le document.

**Comment by Thisisjuke** [comment]
Il faudrait faire un état des lieux savoir si ce ticket est encore pertinent.
Les validators ont été réécris avec Zod et il y a à quelques endroits cette logique de suppression de document.

**Comment by Jdevvv** [comment]
Je vais regarder ça
