### ISSUE TITLE
Activation des badges

### ISSUE THREAD

**Issue by pfreund** [CarbonFight/actions#92]
La logique des badges est implémentée côté Front.

Quelques modifications à prendre en compte côté back :

1. Il y a un nouveau champ "badge" (String) dans la collection users. Celui-ci contient l'id du badge actif (sélectionné par l'utilisateur).

2. Deux badges à passer à true quand l'objectif est atteint (et ne repasse jamais false) :
- **onboardingHowtoFinished** : true quand l'utilisateur à terminé ou passé le tutoriel. Le champ users > skipHowto est à true lorsqu'il termine le tutoriel, à voir s'il faut passer par un champ dans stats ou accéder directement à la collection users
- **onboardingAllChallenges** : true quand tous les défis d'onboarding sont à true. Il y en a pour le moment 8, indiqués avec le tag "En production" sur la page Notion : https://www.notion.so/carbonfight/Espace-Gamification-ad0103051bfb43698d4ff8b1271a0338 onglet "défis".

**Comment by Jdevvv** [comment]
Pour **onboardingHowtoFinished**, je pense que je vais devoir passer par un champ dans stats

**Comment by Jdevvv** [comment]
Yep je vais peut être passer directement par la collection `users` parce que sinon pour suivre le flow actuel faudrait passer par `stats` --> `challenges` --> `badges`
